// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Req
	Rep
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	Left  int32 `protobuf:"varint,1,opt,name=left" json:"left,omitempty"`
	Right int32 `protobuf:"varint,2,opt,name=right" json:"right,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetLeft() int32 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *Req) GetRight() int32 {
	if m != nil {
		return m.Right
	}
	return 0
}

type Rep struct {
	Sum int32 `protobuf:"varint,1,opt,name=sum" json:"sum,omitempty"`
}

func (m *Rep) Reset()                    { *m = Rep{} }
func (m *Rep) String() string            { return proto.CompactTextString(m) }
func (*Rep) ProtoMessage()               {}
func (*Rep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Rep) GetSum() int32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*Req)(nil), "example.Req")
	proto.RegisterType((*Rep)(nil), "example.Rep")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d,
	0xc8, 0x49, 0x55, 0xd2, 0xe7, 0x62, 0x0e, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x49, 0x4d,
	0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x32,
	0xd3, 0x33, 0x4a, 0x24, 0x98, 0xc0, 0x82, 0x10, 0x8e, 0x92, 0x38, 0x48, 0x43, 0x81, 0x90, 0x00,
	0x17, 0x73, 0x71, 0x69, 0x2e, 0x54, 0x3d, 0x88, 0x99, 0xc4, 0x06, 0x36, 0xd9, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xfe, 0xef, 0xd3, 0x0f, 0x6a, 0x00, 0x00, 0x00,
}
