// Code generated by protoc-gen-go.
// source: transport.proto
// DO NOT EDIT!

/*
Package transport is a generated protocol buffer package.

It is generated from these files:
	transport.proto

It has these top-level messages:
	Message
*/
package transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Message is the envelope/wrapper for all messages.
type Message struct {
	// ID is a globally unique message.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Timestamp is the timestamp in nanoseconds with the message was published.
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// Payload is the actual payload being published that will be consumed.
	// This is expected to use protobuf encoding.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Error will be populated if an error occurs within a subscription handler.
	Error string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	// Cause is the ID of a message that resulted in this message being published.
	Cause string `protobuf:"bytes,5,opt,name=cause" json:"cause,omitempty"`
	// Subject is the subject the message is published.
	Subject string `protobuf:"bytes,6,opt,name=subject" json:"subject,omitempty"`
	// Queue is the queue this message was received by.
	Queue string `protobuf:"bytes,7,opt,name=queue" json:"queue,omitempty"`
	// Reply is the inbox ID of the publisher of this message.
	Reply string `protobuf:"bytes,8,opt,name=reply" json:"reply,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Message) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *Message) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Message) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

func (m *Message) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("transport.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0xbf, 0x0a, 0xc2, 0x30,
	0x10, 0xc7, 0x71, 0x52, 0xfb, 0xc7, 0x06, 0x51, 0x08, 0x0e, 0x37, 0x38, 0x14, 0xa7, 0x4e, 0x2e,
	0x3e, 0x87, 0x4b, 0xdf, 0x20, 0x6d, 0x0f, 0xa9, 0xb4, 0x26, 0x5e, 0x92, 0xa1, 0xcf, 0xe7, 0x8b,
	0x49, 0x2e, 0x14, 0xc7, 0xef, 0x87, 0xe3, 0x07, 0x27, 0x4f, 0x9e, 0xf4, 0xdb, 0x59, 0x43, 0xfe,
	0x66, 0xc9, 0x78, 0x73, 0xfd, 0x0a, 0x59, 0x3d, 0xd0, 0x39, 0xfd, 0x44, 0x75, 0x94, 0xd9, 0x34,
	0x82, 0x68, 0x44, 0x5b, 0x77, 0xd9, 0x34, 0xaa, 0x8b, 0xac, 0xfd, 0xb4, 0xa0, 0xf3, 0x7a, 0xb1,
	0x90, 0x35, 0xa2, 0xcd, 0xbb, 0x3f, 0x28, 0x90, 0x95, 0xd5, 0xeb, 0x6c, 0xf4, 0x08, 0xbb, 0x46,
	0xb4, 0x87, 0x6e, 0x4b, 0x75, 0x96, 0x05, 0x12, 0x19, 0x82, 0x9c, 0xa7, 0x52, 0x44, 0x1d, 0x74,
	0x70, 0x08, 0x45, 0x52, 0x8e, 0xb8, 0xe2, 0x42, 0xff, 0xc2, 0xc1, 0x43, 0xc9, 0xbe, 0x65, 0xbc,
	0xff, 0x04, 0x0c, 0x08, 0x55, 0xba, 0xe7, 0x88, 0x4a, 0x68, 0xe7, 0x15, 0xf6, 0x49, 0x39, 0xfa,
	0x92, 0x9f, 0xb9, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x3b, 0x4e, 0xc6, 0xdf, 0x00, 0x00,
	0x00,
}
